version: 0.2
env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: 296062577418.dkr.ecr.ap-south-1.amazonaws.com
    CLUSTER_NAME: demo-cluster-1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476114141387.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t webapp .
      - docker tag webapp:latest 476114141387.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest
      - docker push 476114141387.dkr.ecr.ap-south-1.amazonaws.com/webapp:latest
      - echo Image build and push completed.

  post_build:
    commands:
      - cd ./k8s
      - echo Updating Kubernetes deployment...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl get ns webapp || kubectl create namespace webapp
      - kubectl apply -f k8s-aws.yaml
      - kubectl get pods -n webapp
      - kubectl get svc -n webapp
      - echo Deployment to EKS completed.