apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::476114141387:role/eksctl-demo-cluster-1-cluster-ServiceRole-lNt4IQecuQgR
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::476114141387:role/codebuild-WebAppProject-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::476114141387:user/vivek
      username: vivek
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system